# Generated by Django 4.1.13 on 2024-05-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_review_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=50, null=True)),
                ('source_type', models.CharField(choices=[('1', 'file'), ('2', 'External_API'), ('3', 'Social_Media')], default=1, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='sentiment_class',
        ),
        migrations.AddField(
            model_name='review',
            name='source_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='type_class',
            field=models.TextField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['project_id'], name='app_review_project_766bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['source_id'], name='app_review_source__cb3d63_idx'),
        ),
        migrations.AddField(
            model_name='source',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_sources', to='app.project'),
        ),
    ]
