# Generated by Django 4.1.13 on 2024-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_source_rename_content_review_sentiment_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.IntegerField()),
                ('requirement_text', models.TextField()),
                ('review_id', models.CharField(max_length=255)),
                ('review_text', models.TextField()),
                ('review_polarity', models.TextField()),
                ('similarity_score', models.FloatField()),
            ],
        ),
    ]
