# Generated by Django 4.1.13 on 2024-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='review_id',
        ),
        migrations.AddField(
            model_name='requirements',
            name='negative_reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requirements',
            name='positive_reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
